const express = require('express');
const { authenticate, requireRole } = require('../middleware/auth');
const supabase = require('../lib/supabase');
const router = express.Router();
router.use(authenticate, requireRole('admin'));
router.get('/psychiatrists', async (req, res) => { try { const { data, error } = await supabase.from('profiles').select('id, name').eq('role', 'psychiatrist'); if (error) throw error; res.json({ psychiatrists: data || [] }); } catch (err) { res.status(500).json({ error: err.message }); } });
router.get('/users', async (req, res) => { try { const { data: caregivers, error } = await supabase.from('profiles').select('id, name, is_escalated, assigned_psychiatrist, week_joined').eq('role', 'caregiver'); if (error) throw error; const usersWithBurnout = await Promise.all(caregivers.map(async (user) => { const { data: latestScore } = await supabase.from('burnout_scores').select('week_number, weekly_burnout_score, risk_level').eq('user_id', user.id).order('week_number', { ascending: false }).limit(1).maybeSingle(); return { ...user, latestBurnout: latestScore ? { weekNumber: latestScore.week_number, score: latestScore.weekly_burnout_score, riskLevel: latestScore.risk_level } : null }; })); res.json({ users: usersWithBurnout }); } catch (err) { res.status(500).json({ error: err.message }); } });
router.get('/users/:id/report', async (req, res) => { try { const { data: profile } = await supabase.from('profiles').select('id, name, week_joined').eq('id', req.params.id).single(); const { data: scores } = await supabase.from('burnout_scores').select('*').eq('user_id', req.params.id).order('week_number', { ascending: true }); const { data: evals } = await supabase.from('weekly_evaluations').select('week_number, overall_score, completed_at').eq('user_id', req.params.id).eq('is_pending', false).order('week_number', { ascending: true }); const cycles = []; if (scores && scores.length) { for (let i = 0; i < scores.length; i += 4) { const chunk = scores.slice(i, i + 4); const avg = chunk.reduce((s, w) => s + w.weekly_burnout_score, 0) / chunk.length; const peak = Math.max(...chunk.map(w => w.weekly_burnout_score)); const riskLevel = avg >= 75 ? 'critical' : avg >= 55 ? 'high' : avg >= 30 ? 'moderate' : 'low'; cycles.push({ cycleNumber: Math.floor(i / 4) + 1, weeks: chunk, averageScore: Math.round(avg), peakScore: peak, riskLevel, escalationTriggered: chunk.some(w => w.escalation_triggered) }); } } res.json({ profile, scores: scores || [], evaluations: evals || [], cycles }); } catch (err) { res.status(500).json({ error: err.message }); } });
router.get('/users/:id/burnout', async (req, res) => { try { const { data, error } = await supabase.from('burnout_scores').select('*').eq('user_id', req.params.id).order('week_number', { ascending: true }); if (error) throw error; res.json({ scores: data }); } catch (err) { res.status(500).json({ error: err.message }); } });
router.get('/high-risk', async (req, res) => { try { const { data, error } = await supabase.from('burnout_scores').select('*, profiles!burnout_scores_user_id_fkey(name, email, is_escalated)').in('risk_level', ['high', 'critical']).order('week_number', { ascending: false }); if (error) throw error; const seen = new Set(); const unique = data.filter((s) => { if (seen.has(s.user_id)) return false; seen.add(s.user_id); return true; }); res.json({ highRiskUsers: unique }); } catch (err) { res.status(500).json({ error: err.message }); } });
router.post('/users', async (req, res) => { try { const { name, email, password, role } = req.body; if (!['admin', 'psychiatrist'].includes(role)) return res.status(400).json({ error: 'Invalid role' }); const { data, error } = await supabase.auth.admin.createUser({ email, password, user_metadata: { name, role }, email_confirm: true }); if (error) return res.status(400).json({ error: error.message }); await supabase.from('profiles').upsert({ id: data.user.id, name, role }); res.status(201).json({ user: { id: data.user.id, name, role } }); } catch (err) { res.status(500).json({ error: err.message }); } });
router.post('/escalate/:userId', async (req, res) => { try { const { psychiatristId } = req.body; const { data, error } = await supabase.from('profiles').update({ is_escalated: true, assigned_psychiatrist: psychiatristId || null }).eq('id', req.params.userId).select('id, is_escalated').single(); if (error) throw error; res.json({ success: true, user: data }); } catch (err) { res.status(500).json({ error: err.message }); } });
router.post('/deescalate/:userId', async (req, res) => { try { const { data, error } = await supabase.from('profiles').update({ is_escalated: false, assigned_psychiatrist: null }).eq('id', req.params.userId).select('id, is_escalated').single(); if (error) throw error; res.json({ success: true, user: data }); } catch (err) { res.status(500).json({ error: err.message }); } });
module.exports = router;


